### ISSUE TITLE
Avatar Generation

### ISSUE THREAD

**Issue by malenchite** [malenchite/web-dev-game#17]
This is an interesting npm package I came across. 

https://www.npmjs.com/package/@multiavatar/multiavatar

It allows generation of random avatars from an input string. If we want to have player avatars when they sign up, we could have a simple random string generator. They could keep hitting the randomize button until they find one they like, then save that string to the user profile so that it can be used on the front end without needing to save any images

**Comment by smlisk0630** [comment]
https://tailwindui.com/components/application-ui/elements/avatars
