### ISSUE TITLE
Database API Definition

### ISSUE THREAD

**Issue by malenchite** [malenchite/web-dev-game#19]
We should use this issue to track the interface for backend API calls so that they can be implemented and so that front-end developers have a place they can look to see what they need to send/receive.

**Comment by malenchite** [comment]
I think the user login behavior can be based on the https://github.com/alperg/reactreadinglist-auth example from Alper. This provides four routes for the API:

* /api/user - GET
Send: 
```
{
  user: userid
}
```
Receive:
```
{
  user: userid (or NULL if not logged in)
}
```

* /api/login - POST
Send: 
```
{
  user: userid
  password: password
}
```
Receive:
```
{
  user: userid
}
```

* /api/logout - POST
Send: N/A
Receive:
```
{
  msg: outcome
}
```

* /api/signup - POST
Send: 
```
{
  username
  email
  password
}
```
Receive:
```
{
  error: error on failure
}
OR
{
  username
  email
}
```

**Comment by acinom813** [comment]
https://dev.to/raymag/build-a-quiz-rest-api-with-nodejs-2p64

**Comment by malenchite** [comment]
That's a decent tutorial for how to use Mongoose, but we're not quite there yet. First we just need to define the interface: what we expect the front end to send, and what they expect to receive in return

**Comment by acinom813** [comment]
For the reference of the front-end team. The following calls will yield the designated information.

router.route('/questions/:id')
  .get(questionController.getQuestion);

This will return the question along with its id for the player that the question is GIVEN to

/* Returns all question data  */
router.route('/questions/complete/:id')
  .get(questionController.getCompleteQuestion);
module.exports = router;

This will return the question and answer for the player who is CHECKING the players response.

**Comment by malenchite** [comment]
CARD API

Client requests the details of a specific card by ID
* /api/cards/:id - GET
Send: N/A
Receive:
```
{
  _id
  category: "frontend" or "backend"
  subcategory: OPTIONAL string i.e. "react", "html", etc.
  text: string with the text that is shown to the player
  success: an "effect" object, described below, that occurs if the player succeeds at the card challenge
  failure: an "effect" object, described below, that occurs if the player fails the card challenge
}
```

Effect object:
```
{
  _id
  funding: numerical effect on funding, can be positive or negative
  fep: numerical effect on front end points, can be positive or negative
  bep: numerical effect on back end points, can be positive or negative
  bugs: numerical effect on bug points, can be positive or negative
  special: OPTIONAL string that described more complex things a card might do (primarily here for future use)
}
```
```

**Comment by malenchite** [comment]
Ongoing maintenance has been moved to the wiki: https://github.com/malenchite/web-dev-game/wiki/Database-API
