### ISSUE TITLE
Develop Gameplay

### ISSUE THREAD

**Issue by chrisrisseler** [malenchite/web-dev-game#6]

**Comment by malenchite** [comment]
First pass at some ideas:
* A player has multiple stats that are tracked over the game:
  * Funding points (starts at some fixed value, will go up and down over the game)
  * Front-end points
  * Back-end points
  * Bug points
* On a turn, a player has multiple options:
  * Draw a card (free)
  * Seek funding (free)
  * Develop front-end (costs 1+ funding point)
  * Develop back-end (costs 1+ funding point)
  * Bug fix (costs 1+ funding point)
* The cards will have variable effects, many of which are tied to correctly answering a question correctly. (Maybe positive effects on correct, negative on wrong?) Example effects could be:
  * Gain/lose funding
  * Gain/lose front-end/back-end points
  * Gain/lose bugs
  * Persistent cards with game-long modifiers?
* When seeking funding, a die roll determines how many funding points you get (possibility of 0?)
* When developing, a die roll determines how many development points you get. 
  * Spending extra funding gets you a die modifier (larger die or flat bonus?)
  * Another roll determines how many bugs crop up when you develop (maybe a range of 0 to # of points obtained?)
  * Maybe have the option of answering a front-end/back-end question to add a +1 to the points and a -1 to bugs?
* When bug fixing, a die roll determines how many bug points you lose
* Game lasts for X turns. At the end of the game, players are scored based on
  * Front-end points or back-end points, whichever is lower
  * Minus bug points
  * Tie-breaker is leftover funding?

**Comment by malenchite** [comment]
Questions could be true/false, multiple choice, or open-answer. Rather than automating the response, the answer will be displayed to the opponent. The player answers in the game chat. Once the player answers, the opponent chooses whether they were correct or not and then the answer is shown to the player.

**Comment by malenchite** [comment]
From Chris: https://docs.google.com/document/d/1BmQftFzJlGsCx2iRdyLrtpUFNiMfpx98-3UiDbs7PDc/edit?usp=sharing

**Comment by malenchite** [comment]
Proposal to have Funding be able to go negative from card effects. Negative funding counts as negative VP at score time.

**Comment by malenchite** [comment]
Closing out with initial gameplay decided. Future changes can be opened as a new issue.
