### ISSUE TITLE
Create List of Question

### ISSUE THREAD

**Issue by chrisrisseler** [malenchite/web-dev-game#7]

**Comment by malenchite** [comment]
For MVP we will need 20 questions: 10 frontend and 10 backend. We will want more variety, including breakdown by subcategory, for the final version.

**Comment by malenchite** [comment]
Marking with Phase 2 so that we remember to add more questions before the end.

**Comment by malenchite** [comment]
We currently have 40 questions, 20 front-end, 20 back-end. Subcategories are labeled but presently unused. I'm going to close this and open a new one for future work.
